[build]
  command   = "yarn build"
  environment = {   KONTENT_PROJECT_ID = "FILL", KONTENT_PREVIEW_API_KEY = "FILL", KONTENT_PREVIEW_SECRET = "FILL" }

[[plugins]]
  package = "@netlify/plugin-nextjs"