[build]
  command   = "yarn build"

[build.environment]
  KONTENT_PROJECT_ID = ""
  KONTENT_PREVIEW_API_KEY = ""
  KONTENT_PREVIEW_SECRET = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"